import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { buildManifest } from '../src/lib/manifest';
import { starterPolicy, starterLock } from '../src/lib/starter';
import { CONTENT } from '../src/lib/site-config';

const realNotes = fs
  .readdirSync(CONTENT.questionsDir)
  .filter((f) => f.endsWith('.md'))
  .map((f) => {
    const src = fs.readFileSync(path.join(CONTENT.questionsDir, f), 'utf8');
    return {
      id: f.replace(/\.md$/, ''),
      title: src.match(/^title:\s*(.+)$/m)![1],
      status: src.match(/^status:\s*(\S+)$/m)![1] as
        'working-answer' | 'open' | 'parked',
      updated: src.match(/^updated:\s*(\S+)$/m)![1],
    };
  });

// Every adopting agent previously synthesised this file from prose, so no
// two adoptions had the same shape and none could be tested. Generating it
// from the manifest makes adoption deterministic — and makes these
// assertions possible at all.
describe('starter policy', () => {
  const m = buildManifest(realNotes, '2026-08-23');
  const policy = starterPolicy(m);
  const lock = starterLock(m);

  it('carries every position by id, with claim, enforcement and falsifiers', () => {
    for (const p of m.positions.filter((x) => x.status === 'working-answer')) {
      expect(policy, p.id).toContain(`\`${p.id}\``);
      expect(policy, `${p.id} claim`).toContain(p.claim!);
      expect(policy, `${p.id} falsifier`).toContain(p.falsifiers[0]);
      expect(policy, `${p.id} enforcement`).toContain(p.enforcement![0]);
    }
  });

  it('carries open questions as questions, never as rules', () => {
    for (const p of m.positions.filter((x) => x.status !== 'working-answer')) {
      expect(policy, p.id).toContain(`\`${p.id}\` — ${p.title}`);
    }
    expect(policy.split('## Open questions')[1]).not.toContain('Our rule');
  });

  it('ships usable, with no placeholder left to fill in', () => {
    // The policy generated by hand during the dogfooding pass read
    // "Enforcement: TODO" nine times. A starter that arrives that way is
    // no better than the prose it replaced.
    expect(policy).not.toMatch(/TODO|FIXME|XXX|<[A-Z_]+>/);
  });

  it('locks a digest that matches the manifest, so a fresh adoption is not drift', () => {
    expect(lock.digest).toBe(m.digest);
    for (const p of m.positions)
      expect(lock.positions[p.id], p.id).toBe(p.digest);
    expect(Object.keys(lock.positions)).toHaveLength(m.positions.length);
  });

  it('records the schema version the policy was generated against', () => {
    expect(lock.schemaVersion).toBe(m.schemaVersion);
  });
});
